hard panic when no `#[fallback]` is found
If you're missing the `#[fallback]` variant, you will see an error like
this:

```
error: proc-macro derive panicked
  --> crates/oxide/src/extractor/string_machine.rs:71:45
   |
71 | #[derive(Debug, Clone, Copy, PartialEq, Eq, ClassifyBytes)]
   |                                             ^^^^^^^^^^^^^
   |
   = help: message: A variant marked with #[fallback] is missing
```